import allure
from pages.main_page import MainPage
from pages.login_page import LoginPage
from pages.order_feed_page import OrderFeedPage
from locators.locators import MainPageLocators as MPL, OrderFeedPageLocators as OFPL

@allure.feature("Лента заказов")
class TestOrderFeed:
    @allure.title("Клик на заказ открывает всплывающее окно с деталями")
    def test_order_modal_appears(self, driver, registered_user):
        main_page = MainPage(driver)
        main_page.click_login_button_on_main()
        LoginPage(driver).login(registered_user['email'], registered_user['password'])
        main_page = MainPage(driver)
        main_page.add_bun_to_constructor(MPL.BUN_INGREDIENT, "top")
        main_page.drag_ingredient_to_constructor(MPL.MEAT_INGREDIENT)
        main_page.click_place_order_button()
        main_page.wait_for_visibility(MPL.MODAL_WINDOW)
        main_page.wait_for_element_text_not_equal(MPL.ORDER_ID_IN_MODAL, "9999")
        main_page.close_modal_if_present()
        main_page.click_on_order_feed()
        order_feed_page = OrderFeedPage(driver)
        order_feed_page.wait_for_visibility(OFPL.ORDER_ITEM, 15)
        order_feed_page.click_on_order()
        order_feed_page.wait_for_visibility(OFPL.ORDER_MODAL, 10)
        assert order_feed_page.is_order_modal_displayed()

    @allure.title("Заказы пользователя из раздела 'История заказов' отображаются на странице 'Лента заказов'")
    def test_user_orders_in_feed(self, driver, registered_user):
        main_page = MainPage(driver)
        main_page.click_login_button_on_main()
        LoginPage(driver).login(registered_user['email'], registered_user['password'])
        main_page = MainPage(driver)
        main_page.add_bun_to_constructor(MPL.BUN_INGREDIENT, "top")
        main_page.drag_ingredient_to_constructor(MPL.MEAT_INGREDIENT)
        main_page.click_place_order_button()
        main_page.wait_for_visibility(MPL.MODAL_WINDOW)
        main_page.wait_for_element_text_not_equal(MPL.ORDER_ID_IN_MODAL, "9999")
        order_id = main_page.get_order_id_from_popup()
        main_page.close_modal_if_present()
        main_page.click_on_order_feed()
        order_feed_page = OrderFeedPage(driver)
        order_feed_page.wait_for_visibility(OFPL.ORDER_NUMBERS, 15)
        orders = order_feed_page.get_all_orders_numbers()
        assert order_id in orders, f"Заказ {order_id} не найден в ленте: {orders}"

    @allure.title("При создании нового заказа счётчик 'Выполнено за всё время' увеличивается")
    def test_completed_all_time_counter_increases(self, driver, registered_user):
        main_page = MainPage(driver)
        main_page.click_login_button_on_main()
        LoginPage(driver).login(registered_user['email'], registered_user['password'])
        main_page = MainPage(driver)
        main_page.click_on_order_feed()
        order_feed_page = OrderFeedPage(driver)
        order_feed_page.wait_for_visibility(OFPL.COMPLETED_ALL_TIME_COUNTER)
        initial_value = int(order_feed_page.get_completed_counter_all_time())
        main_page = MainPage(driver)
        main_page.click_on_constructor()
        main_page.add_bun_to_constructor(MPL.BUN_INGREDIENT, "top")
        main_page.drag_ingredient_to_constructor(MPL.MEAT_INGREDIENT)
        main_page.click_place_order_button()
        main_page.wait_for_visibility(MPL.MODAL_WINDOW)
        main_page.wait_for_element_text_not_equal(MPL.ORDER_ID_IN_MODAL, "9999")
        main_page.close_modal_if_present()
        main_page.click_on_order_feed()
        order_feed_page = OrderFeedPage(driver)
        order_feed_page.wait_for_visibility(OFPL.COMPLETED_ALL_TIME_COUNTER)
        new_value = int(order_feed_page.get_completed_counter_all_time())
        assert new_value > initial_value

    @allure.title("При создании нового заказа счётчик 'Выполнено за сегодня' увеличивается")
    def test_completed_today_counter_increases(self, driver, registered_user):
        main_page = MainPage(driver)
        main_page.click_login_button_on_main()
        LoginPage(driver).login(registered_user['email'], registered_user['password'])
        main_page = MainPage(driver)
        main_page.click_on_order_feed()
        order_feed_page = OrderFeedPage(driver)
        order_feed_page.wait_for_visibility(OFPL.COMPLETED_TODAY_COUNTER)
        initial_today = int(order_feed_page.get_completed_counter_today())
        main_page = MainPage(driver)
        main_page.click_on_constructor()
        main_page.add_bun_to_constructor(MPL.BUN_INGREDIENT, "top")
        main_page.drag_ingredient_to_constructor(MPL.MEAT_INGREDIENT)
        main_page.click_place_order_button()
        main_page.wait_for_visibility(MPL.MODAL_WINDOW)
        main_page.wait_for_element_text_not_equal(MPL.ORDER_ID_IN_MODAL, "9999")
        main_page.close_modal_if_present()
        main_page.click_on_order_feed()
        order_feed_page = OrderFeedPage(driver)
        order_feed_page.wait_for_visibility(OFPL.COMPLETED_TODAY_COUNTER)
        new_today = int(order_feed_page.get_completed_counter_today())
        assert new_today > initial_today

    @allure.title("После оформления заказа его номер появляется в разделе 'В работе'")
    def test_order_number_appears_in_work(self, driver, registered_user):
        main_page = MainPage(driver)
        main_page.click_login_button_on_main()
        LoginPage(driver).login(registered_user['email'], registered_user['password'])
        main_page = MainPage(driver)
        main_page.add_bun_to_constructor(MPL.BUN_INGREDIENT, "top")
        main_page.drag_ingredient_to_constructor(MPL.MEAT_INGREDIENT)
        main_page.click_place_order_button()
        main_page.wait_for_visibility(MPL.MODAL_WINDOW)
        main_page.wait_for_element_text_not_equal(MPL.ORDER_ID_IN_MODAL, "9999")
        order_id = main_page.get_order_id_from_popup()
        main_page.close_modal_if_present()
        main_page.click_on_order_feed()
        order_feed_page = OrderFeedPage(driver)
        order_feed_page.wait_for_orders_in_work_not_empty(15)
        orders_in_work = order_feed_page.get_orders_in_work()
        assert order_id in orders_in_work